services:
  - email
  - payment
plugins:
  - name: awsses
    interface: email
  - name: mailgun
    interface: email
  - name: custom
    interface: email
  - name: razorpay
    interface: payment
  - name: stripe
    interface: payment
  - name: custom
    interface: payment
