services:
  - email
  - payment
  - user
plugins:
  - name: appointy
    interface: email
    deployment: microservice
    source: "localhost:9005"
  - name: awsses
    interface: email
    deployment: monolithic # microservice
  - name: mailgun
    interface: email
    deployment: monolithic
  - name: custom
    interface: email
    deployment: microservice
    source: "localhost:9002"
  - name: razorpay
    interface: payment
    deployment: monolithic # microservice
  - name: stripe
    interface: payment
    deployment: monolithic
  - name: custom
    interface: payment
    deployment: microservice
    source: "localhost:9003"
