// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: bookstore/bookstore.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	YearPublished string                 `protobuf:"bytes,4,opt,name=year_published,json=yearPublished,proto3" json:"year_published,omitempty"`
	Plugin        string                 `protobuf:"bytes,5,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookRequest) Reset() {
	*x = AddBookRequest{}
	mi := &file_bookstore_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookRequest) ProtoMessage() {}

func (x *AddBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookRequest.ProtoReflect.Descriptor instead.
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{0}
}

func (x *AddBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *AddBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AddBookRequest) GetYearPublished() string {
	if x != nil {
		return x.YearPublished
	}
	return ""
}

func (x *AddBookRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_bookstore_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *GetBookRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_bookstore_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *DeleteBookRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_bookstore_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_bookstore_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{4}
}

func (x *GenericResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []string               `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_bookstore_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_bookstore_proto_rawDescGZIP(), []int{5}
}

func (x *ListBooksResponse) GetBooks() []string {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_bookstore_bookstore_proto protoreflect.FileDescriptor

const file_bookstore_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x19bookstore/bookstore.proto\x12\tbookstore\x1a\x1cgoogle/api/annotations.proto\"\x91\x01\n" +
	"\x0eAddBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12%\n" +
	"\x0eyear_published\x18\x04 \x01(\tR\ryearPublished\x12\x16\n" +
	"\x06plugin\x18\x05 \x01(\tR\x06plugin\"<\n" +
	"\x0eGetBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\"?\n" +
	"\x11DeleteBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\"*\n" +
	"\x10ListBooksRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\")\n" +
	"\x0fGenericResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\")\n" +
	"\x11ListBooksResponse\x12\x14\n" +
	"\x05books\x18\x01 \x03(\tR\x05books2\xfb\x02\n" +
	"\x10BookstoreService\x12W\n" +
	"\aAddBook\x12\x19.bookstore.AddBookRequest\x1a\x1a.bookstore.GenericResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/books/add\x12W\n" +
	"\aGetBook\x12\x19.bookstore.GetBookRequest\x1a\x1a.bookstore.GenericResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/books/{isbn}\x12V\n" +
	"\tListBooks\x12\x1b.bookstore.ListBooksRequest\x1a\x1c.bookstore.ListBooksResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/books\x12]\n" +
	"\n" +
	"DeleteBook\x12\x1c.bookstore.DeleteBookRequest\x1a\x1a.bookstore.GenericResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/books/{isbn}B\x04Z\x02./b\x06proto3"

var (
	file_bookstore_bookstore_proto_rawDescOnce sync.Once
	file_bookstore_bookstore_proto_rawDescData []byte
)

func file_bookstore_bookstore_proto_rawDescGZIP() []byte {
	file_bookstore_bookstore_proto_rawDescOnce.Do(func() {
		file_bookstore_bookstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookstore_bookstore_proto_rawDesc), len(file_bookstore_bookstore_proto_rawDesc)))
	})
	return file_bookstore_bookstore_proto_rawDescData
}

var file_bookstore_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bookstore_bookstore_proto_goTypes = []any{
	(*AddBookRequest)(nil),    // 0: bookstore.AddBookRequest
	(*GetBookRequest)(nil),    // 1: bookstore.GetBookRequest
	(*DeleteBookRequest)(nil), // 2: bookstore.DeleteBookRequest
	(*ListBooksRequest)(nil),  // 3: bookstore.ListBooksRequest
	(*GenericResponse)(nil),   // 4: bookstore.GenericResponse
	(*ListBooksResponse)(nil), // 5: bookstore.ListBooksResponse
}
var file_bookstore_bookstore_proto_depIdxs = []int32{
	0, // 0: bookstore.BookstoreService.AddBook:input_type -> bookstore.AddBookRequest
	1, // 1: bookstore.BookstoreService.GetBook:input_type -> bookstore.GetBookRequest
	3, // 2: bookstore.BookstoreService.ListBooks:input_type -> bookstore.ListBooksRequest
	2, // 3: bookstore.BookstoreService.DeleteBook:input_type -> bookstore.DeleteBookRequest
	4, // 4: bookstore.BookstoreService.AddBook:output_type -> bookstore.GenericResponse
	4, // 5: bookstore.BookstoreService.GetBook:output_type -> bookstore.GenericResponse
	5, // 6: bookstore.BookstoreService.ListBooks:output_type -> bookstore.ListBooksResponse
	4, // 7: bookstore.BookstoreService.DeleteBook:output_type -> bookstore.GenericResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bookstore_bookstore_proto_init() }
func file_bookstore_bookstore_proto_init() {
	if File_bookstore_bookstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookstore_bookstore_proto_rawDesc), len(file_bookstore_bookstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookstore_bookstore_proto_goTypes,
		DependencyIndexes: file_bookstore_bookstore_proto_depIdxs,
		MessageInfos:      file_bookstore_bookstore_proto_msgTypes,
	}.Build()
	File_bookstore_bookstore_proto = out.File
	file_bookstore_bookstore_proto_goTypes = nil
	file_bookstore_bookstore_proto_depIdxs = nil
}
