plugins:
  - interface: payment
    plugin: stripe
    package: sample/plugins
    type: StripePlugin
    methods:
      - Charge
      - Refund
      - Status
  - interface: notification
    plugin: email
    package: sample/plugins
    type: EmailPlugin
    methods:
      - Send
      - Status
